-- MIT License
--
-- Copyright (c) 2025 Andrew Vasilyev <me@retran.me>
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.
--
-- @file: lua/meow/yarn/config/meta.lua
-- @brief: Type definitions for meow.yarn.nvim configuration
-- @author: Andrew Vasilyev
-- @license: MIT

---@class meow.yarn.Config
---@field window? { width?: number, height?: number, border?: string, preview_height_ratio?: number }
---@field icons? { loading?: string, placeholder?: string, animation_frames?: string[] }
---@field mappings? { jump?: string, toggle?: string, expand?: string, expand_alt?: string, collapse?: string, collapse_alt?: string, show_super_hierarchy?: string, show_sub_hierarchy?: string, quit?: string }
---@field expand_depth? number
---@field preview_context_lines? number
---@field animation_speed? number
---@field hierarchies? { type_hierarchy?: { icons?: { class?: string, struct?: string, interface?: string, default?: string } }, call_hierarchy?: { icons?: { method?: string, func?: string, variable?: string, default?: string } } }

---@type meow.yarn.Config | fun():meow.yarn.Config | nil
vim.g.meow_yarn = vim.g.meow_yarn
